import {Item} from "./item";
import {Settings} from "./settings";
import {Session} from "./session";

export class Order implements IDomainObject {
  key: string; // Key generated by application
  name: string; // Name of person who placed order
  paid: number; // Amount paid
  items: Item[];
  settings: Settings;
  session: Session;

  constructor(orderId: string = "") {
    this.key = orderId;
    this.name = "";
    this.paid = 0;
    this.items = [];
  }

  get count(): number {
    return this.items.length;
  }

  get subtotal(): number {
    return this.items.map(item => item.quantity * item.price)
      .reduce((total, value) => total + value);
  }

  get tax(): number {
    return this.subtotal * this.settings.taxPercent / 100;
  }

  get tip(): number {
    let amt = this.subtotal;
    if (this.settings.tipOption.description === 'Gross') {
      amt += this.tax;
    }
    return amt * this.settings.tipPercent / 100;
  }

  get delivery(): number {
    if (this.session.delivery > 0 && this.session.subtotal > 0) {
      return this.session.delivery * this.subtotal / this.session.subtotal;
    } else {
      return 0;
    }
  }
}
